# Chat action constants for structured logging
MESSAGE_SENT = "MESSAGE_SENT"
MESSAGE_DELETED = "MESSAGE_DELETED"
MESSAGE_FORWARDED = "MESSAGE_FORWARDED"
REACTION_ADDED = "REACTION_ADDED"
REACTION_REMOVED = "REACTION_REMOVED"
MESSAGE_READ = "MESSAGE_READ"
USER_JOINED = "USER_JOINED"
USER_LEFT = "USER_LEFT"
