# Generated by Django 6.0.3 on 2026-03-22 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='messagedeletion',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='messagedeletion',
            name='chat_messag_user_id_08008e_idx',
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_for_users',
            field=models.ManyToManyField(blank=True, related_name='deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageread',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message'),
        ),
        migrations.AddField(
            model_name='messageread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='messagedeletion',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagedeletion',
            name='user',
        ),
        migrations.AddIndex(
            model_name='messageread',
            index=models.Index(fields=['user', 'message'], name='chat_messag_user_id_f12ddc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='messageread',
            unique_together={('message', 'user')},
        ),
        migrations.DeleteModel(
            name='MessageDeletion',
        ),
    ]
