# Generated by Django 6.0.3 on 2026-03-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messageread_alter_messagedeletion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
    ]
