# Generated by Django 6.0.3 on 2026-03-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_conversation_id_alter_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_forwarded',
            field=models.BooleanField(default=False),
        ),
    ]
