# Generated by Django 6.0.3 on 2026-03-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_message_is_forwarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='original_message_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
