# Generated by Django 6.0.3 on 2026-04-06
# Migration: Replace is_online_override (tri-state) with is_visible (boolean)

from django.db import migrations, models


def migrate_presence_data(apps, schema_editor):
    """
    Data migration:
    - is_online_override == False → is_visible = False (hidden)
    - is_online_override in [None, True] → is_visible = True (visible)
    """
    UserPresence = apps.get_model("chat", "UserPresence")
    for presence in UserPresence.objects.all():
        presence.is_visible = False if presence.is_online_override is False else True
        presence.save(update_fields=["is_visible"])


def reverse_presence_data(apps, schema_editor):
    """
    Reverse migration:
    - is_visible == False → is_online_override = False
    - is_visible == True → is_online_override = None
    """
    UserPresence = apps.get_model("chat", "UserPresence")
    for presence in UserPresence.objects.all():
        presence.is_online_override = False if presence.is_visible is False else None
        presence.save(update_fields=["is_online_override"])


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0014_alter_conversationparticipant_id_and_more"),
    ]

    operations = [
        # Step 1: Add new is_visible field
        migrations.AddField(
            model_name="userpresence",
            name="is_visible",
            field=models.BooleanField(default=True),
        ),
        # Step 2: Migrate existing data
        migrations.RunPython(migrate_presence_data, reverse_presence_data),
        # Step 3: Remove old is_online_override field
        migrations.RemoveField(
            model_name="userpresence",
            name="is_online_override",
        ),
    ]
